# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyTwitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Masonry', '~> 1.0.2'

  # Pods for MyTwitter

  target 'MyTwitterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
